name: Karthik DevOps CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Create SSH keys
      run: |
      echo "${{ secrets.SSH_PUBLIC_KEY }}" > terraform/karthikkey.pub
      echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
      chmod 600 ~/.ssh/id_rsa

    - name: Terraform Init
      run: terraform -chdir=terraform init

    - name: Terraform Apply
      run: terraform -chdir=terraform apply -auto-approve

    - name: Get EC2 IP
      id: out
      run: echo "ip=$(terraform -chdir=terraform output -raw public_ip)" >> $GITHUB_OUTPUT

    - name: Install Ansible
      run: sudo apt install ansible -y

    - name: Add EC2 host
      run: ssh-keyscan -H ${{ steps.out.outputs.ip }} >> ~/.ssh/known_hosts

    - name: Run Ansible
      run: |
        echo "[web]" > ansible/inventory
        echo "${{ steps.out.outputs.ip }} ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/id_rsa" >> ansible/inventory
        ansible-playbook -i ansible/inventory ansible/playbook.yml
